apiVersion: v1
kind: Service
metadata:
  # namespace: wp
  labels:
    app: logs
  name: logs
spec:
  type: LoadBalancer
  # loadBalancerIP: 35.192.124.153
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: logs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # namespace: wp
  name: logs
  labels:
    app: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - image: matthewberryhill/mine-logs:pre
          name: logs
          ports:
            - containerPort: 80
              name: logs
